fn main() {
    if c > 4 {
        while c < 4 {
            return 3;
        }

        {
            c += 1;
        } loop x != true;
    } else {
        if hh == false {
            return 10;
        } else if match c > 4 {
            true: {
                return false;
            },
            false: {
                return true;
            }
        } {
            return 4;
        }
    }
}